# Generated by Django 5.2.1 on 2025-05-13 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_usuario_nome_alter_usuario_cpf_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
