# Generated by Django 5.2.1 on 2025-06-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fornecedor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='cpf_cnpj',
            field=models.CharField(default=44444, max_length=18, unique=True),
            preserve_default=False,
        ),
    ]
