# Generated by Django 5.2.1 on 2025-06-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_fornecedor_cpf_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
