# Generated by Django 5.2.1 on 2025-06-05 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_movimentacaoestoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='detalhes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='estoque_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_destino', to='core.local'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='estoque_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_origem', to='core.local'),
        ),
    ]
